[package]
name = "test_time"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
hex="0.4.3"
uint = "0.9.1"
failure = "0.1.8"