[package]
name = "test_sled2"
version = "0.1.0"
authors = ["a <b>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.6"