[package]
name = "test_sqlite"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite="0.26.0"
serde_rusqlite="0.28.0"
serde={version="1.0.130", features=["derive"]}