[package]
name = "test_bytes"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1", features = ["serde"] }
serde= "1.0.137"
serde_json="1.0.81"
hex="0.4.3"